services:
  postgres:
    image: postgres:16-alpine
    container_name: saathi-platform-postgres
    environment:
      POSTGRES_USER: saathi
      POSTGRES_PASSWORD: saathi
      POSTGRES_DB: saathi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: saathi-platform-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
