server:
  port: 8091
spring:
  application:
    name: saathi-notification-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5432/saathi_notification}
    username: ${POSTGRES_USER:saathi}
    password: ${POSTGRES_PASSWORD:saathi}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
